# loop through clients and create a deployment for each
{{- range $client := .Values.clients }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-{{ $client.id }}
  labels:
    app: "mnist-client"
    client-id: "{{ $client.id }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mnist-client"
      client-id: "{{ $client.id }}"
  template:
    metadata:
      labels:
        app: "mnist-client"
        client-id: "{{ $client.id }}"
    spec:
      containers:
        - name: client-{{ $client.id }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          env:
            - name: COMBINER_IP
              value: "{{ $.Values.combinerIP }}"
            - name: CLIENT_TOKEN
              value: "{{ $.Values.clientToken }}"
            - name: AUTH_TOKEN
              value: "{{ $.Values.authToken }}"
            - name: ROUND_NUM
              value: "{{ $.Values.round_num }}"
            - name: MALICIOUS_CLIENTS
              value: "{{ $.Values.malicious.replicas | toString }}"
            - name: BENIGN_CLIENTS
              value: "{{ $.Values.benign.replicas | toString }}"
            - name: DEFENSE_TYPE
              value: "{{ $.Values.defense_type | toString }}"
            - name: LATE_CLIENT_IND
              value: "{{ $.Values.late_client_ind | toJson }}"
            - name: LATE_CLIENT_DELAY
              value: "{{ $.Values.late_client_delay | toString }}"

            - name: CLIENT_ID
              value: "{{ $client.id | toString }}"
            - name: MALICIOUS
              value: "{{ $client.is_malicious | toJson }}"
            - name: ATTACK_TYPE
              value: "{{ $client.attack_type }}"
            - name: BATCH_SIZE
              value: "{{ $client.batch_size | toString }}"
            - name: LR
              value: "{{ $client.lr | toString }}"
            - name: EPOCHS
              value: "{{ $client.epochs | toString }}"
            - name: INFLATION_FACTOR
              value: "{{ $client.inflation_factor | toString }}"
            - name: DATA_ENDPOINT
              value: "{{ $client.data_endpoint | toString }}"
            - name: DATA_ACCESS_KEY
              value: "{{ $client.data_access_key | toString }}"
            - name: DATA_SECRET_KEY
              value: "{{ $client.data_secret_key | toString }}"
            - name: DATA_BUCKET_NAME
              value: "{{ $client.data_bucket_name | toString }}"
            - name: IID
              value: "{{ $client.iid | toString }}"
            - name: BALANCED
              value: "{{ $client.balanced | toString }}"

          args:
            - "--api-url"
            - "{{ $.Values.combinerIP }}"
            - "--token"
            - "{{ $.Values.clientToken }}"
{{- end }}
