image:
  repository: dackevall/mnist-pytorch
  tag: latest
combinerIP: ""
clientToken: ""
authToken: ""
benign:
  replicas: 1
malicious:
  replicas: 1
round_num: 0

clients:
  - id: 1
    is_malicious: false
    attack_type: "label_flip_basic"
    inflation_factor: 2
    batch_size: 32
    epochs: 2
    lr: 0.01
    data_endpoint: "http://"
    data_access_key: ""
    data_secret_key: ""
    data_bucket_name: ""
  - id: 2
    is_malicious: true
    attack_type: "backdoor_35int"
    inflation_factor: 5
    batch_size: 64
    epochs: 3
    lr: 0.005
    data_endpoint: "http://"
    data_access_key: ""
    data_secret_key: ""
    data_bucket_name: ""

defense_type: "none"
